#!/usr/bin/env python3
"""Regenerate plugins/flow-next/schema/flow-config.schema.json (fn-138.1).

CODE is authoritative for keys, types, and defaults (imported from the shipped
flowctl module). DOCS supply descriptions only (DESCRIPTIONS table below).
Hand-editing the committed schema is forbidden - regenerate via this script.

Usage: python3 scripts/gen_flow_config_schema.py [--check]
  --check  exit 1 if the schema on disk is stale (no write)
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "plugins" / "flow-next" / "schema" / "flow-config.schema.json"

sys.path.insert(0, str(REPO / "plugins" / "flow-next" / "scripts"))
import flowctl  # noqa: E402
from flowctl_tracker.resolved_cache import SCOPES  # noqa: E402

# ---------------------------------------------------------------------------
# Descriptions (docs-authored; copy exactly - do not rephrase)
# ---------------------------------------------------------------------------

DESCRIPTIONS: dict[str, str] = {
    "<root>": (
        "Project configuration for flow-next, stored at .flow/config.json. "
        "All keys are optional: flowctl merges these defaults over the file "
        "at read time, so an absent key reads as its documented default. "
        "Generated by scripts/gen_flow_config_schema.py - do not hand-edit "
        "the schema."
    ),
    "$schema": (
        "URL of the JSON Schema this config validates against, stamped by "
        "/flow-next:setup. Inert to flowctl (just a string); editors are "
        "the consumer."
    ),
    "judge": "Optional TypeSafe Jev judgment settings.",
    "judge.enabled": (
        "Enable the optional judge when TYPESAFE_API_KEY is present in the "
        "environment. Default true; false disables requests. Invalid "
        "non-boolean values warn and behave as true. See docs/judge.md."
    ),
    "memory": "Memory system settings (.flow/memory/ categorized learnings).",
    "memory.enabled": (
        "Enable the memory system: skills capture and search categorized "
        "learnings under .flow/memory/."
    ),
    "planSync": (
        "Plan-sync settings (downstream task-spec reconciliation after each "
        "completed task)."
    ),
    "planSync.enabled": (
        "Enable plan-sync after task completion. Off by default (opt-in): "
        "it costs a reconciliation pass after each completed task, and "
        "earns that on specs with dependent tasks. Leave it off and run "
        "/flow-next:sync manually when a task invalidates a downstream "
        "assumption. See docs/running-lean.md."
    ),
    "planSync.crossSpec": (
        "Cross-spec plan-sync: scan other open specs for stale references "
        "after each task (opt-in; increases sync time)."
    ),
    "review": "Review subsystem settings.",
    "review.backend": (
        "Default review backend (codex, copilot, cursor, claude, host, "
        "none) or spec form backend[:model[:effort]], e.g. codex:<model>:high "
        "or claude:<model>:high. cursor folds effort into the model "
        "name (no :effort rung); host and none are bare-only. copilot "
        "accepts no none/minimal effort; claude takes the claude CLI's own "
        "low|medium|high|xhigh|max. If "
        "unset, review commands require --review or FLOW_REVIEW_BACKEND. "
        "Optional: flow-next runs fully without a standing backend. It "
        "costs an out-of-host review pass per round plus a second CLI to "
        "install and authenticate; set it when agent-written diffs merge "
        "without a human reading them line by line, or invoke "
        "/flow-next:impl-review manually instead. See "
        "docs/running-lean.md."
    ),
    "review.fanoutExecution": (
        "First-round CLI review draw scheduling: concurrent (default) or "
        "sequential. Sequential finishes each draw and its sidecars before "
        "starting the next in supplied axis order. Re-review stays single. "
        "Invalid writes and persisted values are rejected before dispatch."
    ),
    "review.copilotDiffDelivery": (
        "Copilot primary-review evidence delivery: native (default) or file. "
        "File writes the frozen reviewed git range under .flow/tmp/claude-review/ "
        "and appends a file-tools instruction without embedding the diff. "
        "Applies to fresh and resumed primary reviews; optional session passes "
        "retain their prior evidence. Invalid values are rejected."
    ),
    "review.reReviewSession": (
        "CLI re-review session policy: resume (built-in default) continues the "
        "previous reviewer conversation; fresh starts one independent reviewer "
        "session after fixes and supplies the full prior-finding container. "
        "An explicit project value overrides FLOW_RE_REVIEW_SESSION, which can "
        "set a user default. --re-review-session overrides both for one review. "
        "First-round fan-out and host review are unchanged."
    ),
    "review.maxIterations": (
        "Cumulative review-round cap per scope (default 8, minimum 1 - the cap "
        "can never be disabled). The env var MAX_REVIEW_ITERATIONS takes "
        "precedence over this key. In an autonomous run (flow --auto) this key "
        "may only lower the cap, so an autonomous agent cannot extend its own "
        "review gate."
    ),
    "scouts": "Planning-scout settings.",
    "scouts.github": "Enable github-scout during planning (requires the gh CLI).",
    "tracker": (
        "Tracker-sync bridge settings (Linear / GitHub / GitLab / Jira). "
        "See docs/tracker-sync.md."
    ),
    "tracker.version": "Tracker config schema version.",
    "tracker.enabled": (
        "Enable the tracker-sync bridge. The bridge is active iff raw "
        "tracker.enabled == true OR raw tracker.type is one of "
        "linear/github/gitlab/jira. Optional: flow-next runs fully without "
        "it. It costs a bidirectional round-trip per enabled lifecycle "
        "event plus a conflict policy and a second place state can be "
        "wrong; enable it when other people need to read or edit status "
        "where they already work, or run /flow-next:tracker-sync manually "
        "and leave the bridge off in between. Spec-only is a first-class "
        "mode. See docs/running-lean.md."
    ),
    "tracker.type": "Tracker backend: linear, github, gitlab, or jira.",
    "tracker.provenance": (
        "Free-form provenance written by the discovery ceremony on "
        "confirmation (who/when/signals)."
    ),
    "tracker.perEvent": (
        "Per-lifecycle-event sync operations. Schema default off for every "
        "event, so a bare enabled=true fires no lifecycle sync; the "
        "/flow-next:tracker-sync discovery ceremony activates events opt-out "
        "when you hook up the bridge."
    ),
    "tracker.perEvent.capture": (
        "Sync op fired when a spec is captured: off | pull | push | "
        "reconcile | comment."
    ),
    "tracker.perEvent.interview": (
        "Sync op fired after an interview updates a spec: off | pull | push "
        "| reconcile | comment."
    ),
    "tracker.perEvent.plan": (
        "Sync op fired after planning: off | pull | push | reconcile | comment."
    ),
    "tracker.perEvent.work": "Work-lifecycle sync events.",
    "tracker.perEvent.work.firstClaim": (
        "Sync op fired on a task's first claim: off | pull | push | "
        "reconcile | comment."
    ),
    "tracker.perEvent.work.done": (
        "Sync op fired when a task completes: off | pull | push | reconcile "
        "| comment."
    ),
    "tracker.perEvent.makePr": (
        "Sync op fired when make-pr opens a PR: off | pull | push | "
        "reconcile | comment. The PR link + In Review push is unconditional "
        "whenever the bridge is active."
    ),
    "tracker.perEvent.resolvePr": (
        "Sync op fired after resolve-pr: off | pull | push | reconcile | "
        "comment."
    ),
    "tracker.perEvent.completionReview": (
        "Sync op fired after the spec completion review: off | pull | push "
        "| reconcile | comment. The ceremony seeds comment (verdict + R-ID "
        "coverage; never terminal Done)."
    ),
    "tracker.perEvent.qa": (
        "Post the /flow-next:qa ship verdict as a tracker comment: off | "
        "comment only. comment is the only sensible verb for a verdict; the "
        "QA skill treats any non-off value as comment. Not switched on by "
        "the ceremony's default-on set - QA-specific opt-in."
    ),
    "tracker.perEvent.land": "Land-lifecycle sync events.",
    "tracker.perEvent.land.merged": (
        "Post-merge touchpoint for /flow-next:land. Active-by-default "
        "whenever the bridge is active (a real merge is the only event that "
        "legitimately projects terminal Done); this leaf does not gate the "
        "merge-gated status write. Land writes no local sync receipt, timestamp, "
        "or verdict comment. A closed spec on an open PR remains In Review."
    ),
    "tracker.charts": (
        "Optional chart lifecycle projection (fn-135). String-enum off|on, "
        "NOT a bool: only the literal on projects charts as parent issues "
        "with decision children through the tracker facade. Local chart "
        "operations always succeed when off or when the bridge is inactive."
    ),
    "tracker.perTracker": (
        "Per-tracker linkage written by the discovery ceremony on "
        "confirmation. Open: tracker types add their own keys here."
    ),
    "tracker.perTracker.teamId": "Linear team id.",
    "tracker.perTracker.projectId": "Linear project id.",
    "tracker.perTracker.labelMap": "Label linkage map (tracker-specific shape).",
    "tracker.perTracker.priorityMap": (
        "Priority linkage map (tracker-specific shape)."
    ),
    "tracker.perTracker.repo": (
        "GitHub repo as owner/name, written by the discovery ceremony "
        "(machine-written; not part of the seeded defaults)."
    ),
    "tracker.perTracker.project": (
        "GitLab group/subgroup/project path (URL-encoded once for the API, "
        "never double-encoded)."
    ),
    "tracker.perTracker.host": (
        "Self-managed GitLab base URL. null resolves from glab config / "
        "CI_SERVER_URL; gitlab.com is never assumed."
    ),
    "tracker.perTracker.baseUrl": (
        "Jira site base URL (Cloud or DC/Server). The JIRA_BASE_URL env var "
        "overrides it at runtime."
    ),
    "tracker.perTracker.projectKey": (
        "Jira project key (the JQL / listOpenIssues scope)."
    ),
    "tracker.perTracker.authScheme": (
        "Jira auth shape decided once at the discovery ceremony: cloud-basic "
        "(Cloud HTTP-basic email:API_TOKEN) or bearer-pat (DC/Server bearer "
        "PAT). Credentials still read from env each run, never stored here."
    ),
    "tracker.perTracker.owner": (
        "GitHub repository owner (discovery-fingerprint input; dynamic "
        "per.get read via _FINGERPRINT_KEYS)."
    ),
    "tracker.perTracker.issueType": (
        "Jira issue type (name or id) for created issues; a configured value "
        "that does not resolve against the live project is an error."
    ),
    "tracker.perTracker.blocksLinkType": (
        "GitLab link type used for blocks relations (e.g. blocks); probe and "
        "mutation use the same resolved name."
    ),
    "tracker.perTracker.preferredTransport": (
        "Linear transport preference (mcp routes through the MCP "
        "continuation; anything else uses HTTP)."
    ),
    "tracker.perTracker.transport": (
        "Legacy alias for preferredTransport (read second)."
    ),
    "tracker.transport": (
        "HTTP transport tuning for tracker calls (dict-read in "
        "flowctl_tracker)."
    ),
    "tracker.transport.timeoutS": "Per-request timeout in seconds (0-600).",
    "tracker.transport.maxRetries": "Retry attempts per call.",
    "tracker.transport.backoffCapS": "Backoff cap in seconds.",
    "tracker.transport.concurrency": "Max concurrent tracker calls.",
    "tracker.perTracker.apiVersion": (
        "Jira REST API version. null until the resolver pins 2; migration "
        "converges a legacy 3 to 2."
    ),
    "tracker.perTracker.sslVerify": (
        "Verify TLS certificates against Jira. false is an explicit opt-out "
        "for a self-hosted internal-CA / self-signed cert (JIRA_SSL_VERIFY "
        "env overrides)."
    ),
    "tracker.perTracker.statusMap": (
        "Legacy normalized-status to Jira status map ({name}/{id}; id "
        "preferred - names are project-renamable). Live entries migrate into "
        "tracker.resolved.destination.statusIds; dead entries are dropped "
        "with a warning."
    ),
    "tracker.staleAfterHours": (
        "Staleness threshold (hours) consumed by sync list-stale."
    ),
    "tracker.conflictTiebreak": (
        "Status who-wins tiebreak: flow-wins | tracker-wins | always-ask. "
        "Strict enum: invalid CLI writes are rejected; malformed persisted "
        "values fail before status work. In autonomous mode always-ask "
        "resolves to queue, not prompt."
    ),
    "tracker.readyState": (
        "Readiness projection: the tracker workflow state meaning ready for "
        "work (a Linear state name, Jira status name, or a GitHub/GitLab "
        "label). When set, pull-side sync projects it onto the local spec "
        "ready flag - one-way, tracker is authoritative. null = projection "
        "off."
    ),
    "tracker.specIds": (
        "Id scheme for new specs when a tracker bridge is active: flow "
        "(native fn-N) or tracker (tracker-keyed KEY-N-slug / synthetic gh-N "
        "/ gl-N). Strict enum on write; malformed on-disk values fail closed "
        "to flow. Not materialized at init so setup can detect never-asked "
        "via a raw null read."
    ),
    "tracker.resolved": (
        "Persisted runtime facts written by flowctl tracker resolve "
        "(destination + capability cache). Machine-written, atomic, "
        "partially-absent-by-design during migration - never hand-edit; "
        "refresh with flowctl tracker resolve."
    ),
    "tracker.resolved.destination": (
        "Resolved destination facts. Fields vary by tracker type (GitHub "
        "owner/repo; GitLab projectId/projectPath/host/namespaceId; Linear "
        "teamId/teamKey/stateIds/labelIds; Jira baseUrl/projectKey/projectId/"
        "issueTypeId/apiVersion/style/statusIds), so no per-provider fields "
        "are required here."
    ),
    "tracker.resolved.destination.statusIds": (
        "Normalized status slots (todo, in_progress, done; optional provider "
        "slots) mapped to provider status ids."
    ),
    "tracker.resolved.destination.stateIds": (
        "Normalized state slots mapped to provider state ids (Linear)."
    ),
    "tracker.resolved.capabilities": (
        "Provider capability booleans (e.g. attachments, blockedBy, "
        "subIssues, deleteIssue) from the provider's static table."
    ),
    "tracker.resolved.scopeResolvedAt": (
        "Per-scope resolution timestamps, keyed by exactly the four "
        "canonical scopes. Scope timestamps are independent: a destination "
        "refresh cannot make capabilities or status ids look fresh."
    ),
    "tracker.resolved.resolvedAt": (
        "Non-null only when all required destination fields, required "
        "normalized slots, and capability booleans are present."
    ),
    "land": "/flow-next:land settings for one named pull request. Unknown legacy keys are ignored.",
    "land.patienceMinutes": (
        "Minutes since the last push to wait, so review bots can post, when no human authorized the merge in-session."
    ),
    "land.mergeVerdictCommand": (
        "Optional merge-verdict command run once after the other merge gates pass. "
        "Any non-zero result, including missing, unexecutable or timed-out commands, "
        "blocks merging. Unset, null and empty string disable it."
    ),
    "makePr": "/flow-next:make-pr export settings.",
    "makePr.derivedPaths": (
        "Optional derived-file classification rules for the make-pr export: "
        "bucket names (dualCopy, mirror, state) mapped to arrays of rules "
        "({path|prefix, source}). A configured value fully replaces "
        "flow-next's built-in default shapes; never required and not part "
        "of the seeded defaults."
    ),
    "pipeline": "Pilot pipeline stage gates.",
    "pipeline.qa": (
        "Optional live QA stage. String-enum off | on | auto, NOT a bool; "
        "any other value, including bool true, is OFF. Default off. What "
        "each value does is defined by the flow skill's gate-selection "
        "reference (skills/flow-next-flow/references/gate-selection.md); "
        "flowctl stores the value and never interprets it. See "
        "docs/running-lean.md."
    ),
    "chart": (
        "Chart discovery settings (fn-135): size ceiling at charting time "
        "and stale-claim recovery threshold."
    ),
    "chart.maxDecisions": (
        "Charting-time decision ceiling (default 12). chart create with an "
        "initial-map refuses past this count without --force-size --reason. "
        "Later sharpening may grow past it."
    ),
    "chart.claimStaleAfter": (
        "Stale-claim age threshold in hours (default 24). "
        "release-claim --break-stale --reason is allowed only after a claim "
        "is at least this old; always audited (actor, prior owner, age, reason)."
    ),
    "features": "Feature-map settings (fn-262): the maintain-pass due trigger.",
    "features.staleAfterCommits": (
        "Due threshold (default 50). flowctl features status reports the "
        "feature map due a maintain pass when a feature file's last proof is "
        "at least this many default-branch commits old, counting only commits "
        "that change a file outside .flow/ and docs."
    ),
    "pilot": "/flow-next:flow --auto settings (the pilot key name is kept).",
    "pilot.autonomy": (
        "Backlog mode for flow --auto (--backlog forces it per run). Scalar string-enum (ready | backlog), "
        "NOT a bool. ready = select only already-ready specs. Only the "
        "literal backlog widens selection to the whole open backlog; any "
        "other value stays ready. Backlog mode never authors a spec, never "
        "sets ready, and grants no merge authority."
    ),
    "pilot.gateClasses": (
        "Backlog-mode force-gate: class names (e.g. risky, prod-config) that "
        "force surfacing before action - a matching item is parked with a "
        "question instead of advanced full-auto. Empty = full-auto for every "
        "workable item."
    ),
}

_PER_EVENT = ["off", "pull", "push", "reconcile", "comment"]
_QA_EVENT = ["off", "comment"]


def _default_leaves(obj: Any, prefix: str = "") -> dict[str, Any]:
    """Walk get_default_config() leaves (empty dict/list are leaves)."""
    out: dict[str, Any] = {}
    if isinstance(obj, dict):
        if not obj:
            out[prefix] = obj
            return out
        for key, val in obj.items():
            path = f"{prefix}.{key}" if prefix else key
            out.update(_default_leaves(val, path))
        return out
    out[prefix] = obj
    return out


def _review_backend_fragment() -> dict:
    model_backends = sorted(
        b for b, r in flowctl.BACKEND_REGISTRY.items() if r.get("models")
    )
    effort_backends = sorted(
        b
        for b, r in flowctl.BACKEND_REGISTRY.items()
        if r.get("models") and r.get("efforts")
    )
    model_only = sorted(set(model_backends) - set(effort_backends))
    # One pattern branch PER effort backend, each with that backend's own
    # effort set - a union alternation would accept e.g. copilot:<m>:none,
    # which flowctl rejects at parse time. Backend names are re.escape()d so
    # a future name carrying a regex metachar cannot corrupt the pattern.
    effort_branches = [
        {
            "type": "string",
            "pattern": (
                # Model component OPTIONAL: BackendSpec.parse accepts
                # effort-only (`codex::high`) and bare-colon (`codex:`)
                # shapes - runtime-valid configs must not fail editors.
                f"^{re.escape(b)}:[^:\\s]*"
                f"(:({'|'.join(sorted(flowctl.BACKEND_REGISTRY[b]['efforts']))})?)?$"
            ),
        }
        for b in effort_backends
    ]
    only_alt = "|".join(re.escape(b) for b in model_only)
    return {
        "anyOf": [
            {"type": "null"},
            {"enum": list(flowctl.VALID_BACKENDS)},
            # Degenerate-but-runtime-valid: a bare backend with ONE trailing
            # colon (`host:`) parses to the bare backend.
            {
                "type": "string",
                "pattern": "^(" + "|".join(re.escape(b) for b in sorted(flowctl.VALID_BACKENDS)) + "):{1,2}$",
            },
            *effort_branches,
            {"type": "string", "pattern": f"^({only_alt}):[^:\\s]*:?$"},  # model-only: optional trailing empty effort colon
        ],
    }



def _scope_resolved_at_fragment() -> dict:
    """SCOPES keys include dots - bake as a leaf so path-split stays safe."""
    props: dict[str, Any] = {}
    for scope in SCOPES:
        props[scope] = {
            "type": "string",
            "description": (
                f"ISO timestamp of the last successful {scope} resolution."
            ),
        }
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": props,
    }


def _status_map_fragment() -> dict:
    return {
        "type": "object",
        "additionalProperties": {
            "type": "object",
            "properties": {
                "name": {"type": "string"},
                "id": {"type": ["string", "integer"]},
            },
            "additionalProperties": True,
        },
    }


def _assert_unique_paths(table: list[tuple[str, dict]]) -> None:
    """A duplicate TABLE path silently clobbers the earlier node in the
    assembler (parent_props[key] = node) - fail loudly instead (PR #280 r5)."""
    seen: set[str] = set()
    for path, _ in table:
        if path in seen:
            raise AssertionError(f"duplicate TABLE path: {path}")
        seen.add(path)


def _build_table() -> list[tuple[str, dict]]:
    """Ordered TABLE: dotted path -> container or leaf fragment."""
    return [
        ("$schema", {"type": "string"}),
        ("judge", {"kind": "object", "open": False}),
        ("judge.enabled", {"type": "boolean"}),
        ("memory", {"kind": "object", "open": False}),
        ("memory.enabled", {"type": "boolean"}),
        ("planSync", {"kind": "object", "open": False}),
        ("planSync.enabled", {"type": "boolean"}),
        ("planSync.crossSpec", {"type": "boolean"}),
        ("review", {"kind": "object", "open": False}),
        ("review.backend", _review_backend_fragment()),
        ("review.fanoutExecution", {"type": "string", "enum": list(flowctl.REVIEW_POLICY_VALUES["review.fanoutExecution"])}),
        ("review.copilotDiffDelivery", {"type": "string", "enum": list(flowctl.REVIEW_POLICY_VALUES["review.copilotDiffDelivery"])}),
        ("review.reReviewSession", {"type": "string", "enum": list(flowctl.REVIEW_POLICY_VALUES["review.reReviewSession"])}),
        ("review.maxIterations", {"type": "integer", "minimum": 1}),
        ("scouts", {"kind": "object", "open": False}),
        ("scouts.github", {"type": "boolean"}),
        ("tracker", {"kind": "object", "open": False}),
        ("tracker.version", {"type": "integer"}),
        ("tracker.enabled", {"type": "boolean"}),
        (
            "tracker.type",
            {"enum": ["linear", "github", "gitlab", "jira", None]},
        ),
        ("tracker.provenance", {"type": ["string", "null"]}),
        ("tracker.perEvent", {"kind": "object", "open": False}),
        ("tracker.perEvent.capture", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.interview", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.plan", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.work", {"kind": "object", "open": False}),
        ("tracker.perEvent.work.firstClaim", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.work.done", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.makePr", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.resolvePr", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.completionReview", {"enum": list(_PER_EVENT)}),
        ("tracker.perEvent.qa", {"enum": list(_QA_EVENT)}),
        ("tracker.perEvent.land", {"kind": "object", "open": False}),
        ("tracker.perEvent.land.merged", {"enum": list(_PER_EVENT)}),
        ("tracker.charts", {"enum": ["off", "on"]}),
        ("tracker.perTracker", {"kind": "object", "open": True}),
        ("tracker.perTracker.teamId", {"type": ["string", "null"]}),
        ("tracker.perTracker.projectId", {"type": ["string", "null"]}),
        (
            "tracker.perTracker.labelMap",
            {"type": "object", "additionalProperties": True},
        ),
        (
            "tracker.perTracker.priorityMap",
            {"type": "object", "additionalProperties": True},
        ),
        ("tracker.perTracker.repo", {"type": ["string", "null"]}),
        ("tracker.perTracker.project", {"type": ["string", "null"]}),
        ("tracker.perTracker.host", {"type": ["string", "null"]}),
        ("tracker.perTracker.baseUrl", {"type": ["string", "null"]}),
        ("tracker.perTracker.projectKey", {"type": ["string", "null"]}),
        (
            "tracker.perTracker.authScheme",
            {"enum": ["cloud-basic", "bearer-pat", None]},
        ),
        ("tracker.perTracker.apiVersion", {"type": ["integer", "null"]}),
        # set_config coerces digit-only args to int and the resolver compares
        # str(configured) - numeric ids are a supported CLI shape.
        ("tracker.perTracker.owner", {"type": ["string", "null"]}),
        ("tracker.perTracker.issueType", {"type": ["string", "integer", "null"]}),
        ("tracker.perTracker.blocksLinkType", {"type": ["string", "null"]}),
        ("tracker.perTracker.preferredTransport", {"type": ["string", "null"]}),
        ("tracker.perTracker.transport", {"type": ["string", "null"]}),
        ("tracker.perTracker.sslVerify", {"type": "boolean"}),
        ("tracker.perTracker.statusMap", _status_map_fragment()),
        ("tracker.staleAfterHours", {"type": "integer"}),
        (
            "tracker.conflictTiebreak",
            {"enum": sorted(flowctl.TRACKER_CONFLICT_TIEBREAK_VALUES)},
        ),
        ("tracker.readyState", {"type": ["string", "null"]}),
        (
            "tracker.specIds",
            {"enum": sorted(flowctl.TRACKER_SPEC_IDS_VALUES)},
        ),
        (
            "tracker.transport",
            # Dict-read tuning block (resolve_verb reads it whole) - open so
            # future knobs never invalidate configs; known keys typed.
            {"kind": "object", "open": True, "nullable": True},
        ),
        ("tracker.transport.timeoutS", {"type": ["number", "null"]}),
        ("tracker.transport.maxRetries", {"type": ["integer", "null"]}),
        ("tracker.transport.backoffCapS", {"type": ["number", "null"]}),
        ("tracker.transport.concurrency", {"type": ["integer", "null"]}),
        ("tracker.resolved", {"kind": "object", "open": True}),
        ("tracker.resolved.destination", {"kind": "object", "open": True}),
        (
            "tracker.resolved.destination.statusIds",
            {"type": "object", "additionalProperties": {"type": "string"}},
        ),
        (
            "tracker.resolved.destination.stateIds",
            {"type": "object", "additionalProperties": {"type": "string"}},
        ),
        (
            "tracker.resolved.capabilities",
            {
                "type": "object",
                # Capability flags are booleans, but GitLab's resolver also
                # persists a machine-written `_source` provenance object
                # alongside them (resolved_cache.apply_scope_result) - model
                # it explicitly so a valid GitLab config never fails editors.
                "properties": {
                    "_source": {
                        "type": "object",
                        "description": "Machine-written capability provenance (which probe/endpoint established each flag); GitLab's resolver persists it alongside the boolean capability keys.",
                    },
                },
                "additionalProperties": {"type": "boolean"},
            },
        ),
        ("tracker.resolved.scopeResolvedAt", _scope_resolved_at_fragment()),
        ("tracker.resolved.resolvedAt", {"type": ["string", "null"]}),
        ("land", {"kind": "object", "open": True}),
        ("land.patienceMinutes", {"type": "integer"}),
        ("land.mergeVerdictCommand", {"type": ["string", "null"]}),
        ("makePr", {"kind": "object", "open": False}),
        (
            "makePr.derivedPaths",
            {
                "type": "object",
                "additionalProperties": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": {"type": "string"},
                    },
                },
            },
        ),
        ("pipeline", {"kind": "object", "open": False}),
        ("pipeline.qa", {"enum": ["off", "on", "auto"]}),
        ("chart", {"kind": "object", "open": False}),
        ("chart.maxDecisions", {"type": "integer"}),
        ("chart.claimStaleAfter", {"type": "number"}),
        ("features", {"kind": "object", "open": False}),
        ("features.staleAfterCommits", {"type": "integer", "minimum": 1}),
        ("pilot", {"kind": "object", "open": False}),
        ("pilot.autonomy", {"enum": ["ready", "backlog"]}),
        (
            "pilot.gateClasses",
            # The documented CLI form `flowctl config set pilot.gateClasses
            # risky` persists a BARE STRING which the pilot workflow
            # normalizes to one class - scalar and array are both supported.
            {
                "anyOf": [
                    {"type": "string"},
                    {"type": "array", "items": {"type": "string"}},
                ]
            },
        ),
    ]


def compute() -> dict:
    """Build the schema object (insertion order is property order)."""
    defaults = _default_leaves(flowctl.get_default_config())
    table = _build_table()
    _assert_unique_paths(table)

    schema: dict[str, Any] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://flow-next.dev/schema/flow-config.schema.json",
        "title": "flow-next .flow/config.json",
        "description": DESCRIPTIONS["<root>"],
        "type": "object",
        "additionalProperties": False,
        "properties": {},
    }

    defaulted: set[str] = set()
    for path, spec in table:
        if path not in DESCRIPTIONS:
            raise AssertionError(f"missing description for TABLE path {path!r}")
        parts = path.split(".")
        parent_props = schema["properties"]
        for part in parts[:-1]:
            if part not in parent_props:
                raise AssertionError(
                    f"parent missing for {path!r} (need {part!r} first)"
                )
            parent_props = parent_props[part]["properties"]
        key = parts[-1]

        if spec.get("kind") == "object":
            node: dict[str, Any] = {
                "description": DESCRIPTIONS[path],
                # nullable: validator-accepted whole-block clear paths persist
                # null and must stay valid.
                "type": ["object", "null"] if spec.get("nullable") else "object",
                "additionalProperties": bool(spec["open"]),
                "properties": {},
            }
        else:
            node = {"description": DESCRIPTIONS[path]}
            node.update(spec)
            if path in defaults:
                node["default"] = defaults[path]
                defaulted.add(path)

        parent_props[key] = node

    if defaulted != set(defaults):
        missing = sorted(set(defaults) - defaulted)
        extra = sorted(defaulted - set(defaults))
        raise AssertionError(
            "TABLE leaf defaults diverge from get_default_config() leaves: "
            f"missing_defaults={missing} unexpected_defaults={extra}"
        )
    return schema


def render() -> str:
    """Deterministic JSON text (exactly one trailing newline)."""
    return (
        json.dumps(
            compute(),
            indent=2,
            ensure_ascii=True,
            separators=(",", ": "),
        )
        + "\n"
    )


def main() -> int:
    rendered = render()
    if "--check" in sys.argv[1:]:
        on_disk = OUT.read_bytes() if OUT.exists() else b""
        if on_disk != rendered.encode("utf-8"):
            print(
                "flow-config.schema.json is stale; "
                "run scripts/gen_flow_config_schema.py",
                file=sys.stderr,
            )
            return 1
        print("flow-config.schema.json is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_bytes(rendered.encode("utf-8"))
    print(f"wrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
